Composer: avoid writing a lock file
PHPCSStandards/composer-installer pull request #218
Opened 2024-04-19 11:28 UTC by fredden

## Proposed Changes

When working with this repository as a developer, we should be using the latest compatible packages. By writing a lock file for Composer, we may get into a state where we are "stuck" on an older version of a dependency. This change avoids such a situation by telling Composer to not write out a lock file in the project.

2024-04-19 12:09 UTC, jrfnl requested changes
Thanks @fredden for this PR! I agree this is a good change.

To allow for merging this PR, however, a small tweak need to be made to the `securitycheck.yml` workflow which relies on the `composer.lock` file.
 I think an extra step needs to be added to the workflow, before the "compose install" step, to remove this key from the config. that should allow for the workflow to continue to work and be useful.

2024-04-21 16:34 UTC, jrfnl approved these changes
LGTM 👍🏻

2024-05-03 07:32 UTC, Potherca approved these changes

2024-05-03 13:07 UTC, jrfnl commented
Merging. The build failures against PHP 8.4 are unrelated to this PR and will be addressed separately via PR #219.

2024-05-03 13:07 UTC, merged